import Transition from "@/components/Transitions/Transition";
import Head from "next/head";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Mugunth | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition>
        <h1>Contact</h1>
      </Transition>
    </>
  );
}
