import Image from "next/image";
import Transition from "@/components/Transitions/Transition";
import Head from "next/head";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Mugunth | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition>
        <div className="bg-image">
          <Image
            src="/images/bg.jpg"
            objectFit="cover"
            height={500}
            width={1000}
            alt="about-bg"
            quality={100}
            className="contact-bg"
          />
        </div>
        
        <div className="contact-container">
          <section className="contact-form">
            drop me an mail
          </section>
        </div>
      </Transition>
    </>
  );
}
