import Head from 'next/head'
import Transition from '@/components/Transitions/Transition'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mugunth | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition>
        <h1>Home</h1>
      </Transition>
    </>
  )
}
