import Head from "next/head";
import Transition from "@/components/Transitions/Transition";
import "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mugunth | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition>
        <div className="hero-wrapper">
          <div className="hero-text-wrapper">
            <div className="hero-text">
              <h1 className="design">design</h1>
              <span className="dot"></span>
              <h1 className="develop">develop</h1>
            </div>
          </div>
        </div>
      </Transition>
    </>
  );
}
