const work = [
    {
    id: "01",
      title: "Zephyrus",
      text: "A Cross Platform Social Media Application",
      type: "Design & Development",
      image: "1.jpg",
      year: 2024,
      isLive: true,
      url: "https://zephyrus.netlify.app/",
      github: "https://github.com/Mugunth140/zephyrus-frontend.git",
    },
    {
      id: "02",
      title: "Portfolio 2021",
      text: "Previous Version of My Portfolio",
      type: "Design & Development",
      image: "2.jpg",
      year: 2021,
      isLive: true,
      url: "https://zephyrus.netlify.app/",
      github: "https://github.com/Mugunth140/zephyrus-frontend.git",
    },
    {
      id: "03",
      title: "Weather Forecast",
      text: "Weather Forecasting Web Application",
      type: "Design & Development",
      image: "3.jpg",
      year: 2022,
      isLive: true,
      url: "https://zephyrus.netlify.app/",
      github: "https://github.com/Mugunth140/zephyrus-frontend.git",
    },
    {
      id: "04",
      title: "Rock Paper Scissor",
      text: "A Simple Rock Paper Scissor Web Based Game",
      type: "Design & Development",
      image: "4.jpg",
      year: 2023,
      isLive: true,
      url: "https://zephyrus.netlify.app/",
      github: "https://github.com/Mugunth140/zephyrus-frontend.git",
    },
    {
      id: "05",
      title: "E-commerce Website",
      text: "A Simple E-commerce Website",
      type: "Design",
      image: "5.jpg",
      year: 2024,
      isLive: true,
      url: "https://zephyrus.netlify.app/",
      github: "https://github.com/Mugunth140/zephyrus-frontend.git",
    },
    {
      id: "06",
      title: "Personal Website",
      text: "My Personal Website",
      type: "Development",
      image: "6.jpg",
      year: 2023,
      isLive: true,
      url: "https://zephyrus.netlify.app/",
      github: "https://github.com/Mugunth140/zephyrus-frontend.git",
    }
  ];

  export default work;
