import Page from '@/components/Layout'
import Head from 'next/head'

export default function Work() {
  return (
    <>
      <Head>
        <title>Mugunth | Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page >
        <h1>Work</h1>
      </Page>
    </>
  )
}